[project]
name = "mcp-mysql-1password-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
    "fastmcp>=2.0.0",
    "PyMySQL>=1.1.0",
]
